permalink: /blog/:title

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : vameri
description: UX Designer, Desenvolvedor Front End e Coordenador do GUFERS, entusiasta em tecnologia e na comunidade.
keywords: site vameri, UX Designer, Front End, desenvolvedor web, GUFERS
author : 
  name : vameri
  email : vameri@pm.me
  github : https://github.com/vameri
  linkdin: http://br.linkedin.com/in/vameri

production_url : http://vameri.github.io/
